import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from "@clerk/themes";
import Link from "next/link";

const geistSans = Geist({
     variable: "--font-geist-sans",
     subsets: ["latin"],
});

const geistMono = Geist_Mono({
     variable: "--font-geist-mono",
     subsets: ["latin"],
});

export const metadata: Metadata = {
     title: "Create Next App",
     description: "Generated by create next app",
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <ClerkProvider
               appearance={{
                    baseTheme: neobrutalism,
               }}
          >
               <html lang="en" suppressHydrationWarning>
                    <body
                         suppressHydrationWarning
                         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                    >
                         <header className="border-b">
                              <div className="max-w-6xl mx-auto p-4 flex items-center gap-6">
                                   <Link href="/" className="font-semibold">
                                        Port
                                   </Link>
                                   <nav className="text-sm flex gap-4">
                                        <Link href="/dashboard">Dashboard</Link>
                                   </nav>
                              </div>
                         </header>
                         {children}
                    </body>
               </html>
          </ClerkProvider>
     );
}
